export const CORE_VERSION = '0.1.0';
export * from './protocol/types';
export { Emitter } from './protocol/emitter';
export { normalizeServerEvent } from './protocol/normalize';
export { bytesToBase64, base64ToBytes } from './audio/base64';
export { WsTransport, type WsLike, type WsTransportOptions } from './protocol/wsTransport';
export { TranscriptModel, type TranscriptSegment, type SegmentStatus } from './session/transcriptModel';
export { SessionLogger, fnv1a, type SessionLoggerOptions } from './session/sessionLogger';
export { downsampleTo16kPcm16 } from './audio/resample';
export { PcmChunker } from './audio/pcmChunker';
export { LANGUAGES, supportsAudioOutput, type LanguageInfo } from './i18n/languages';
export { pcm16ToWav, wavDurationSeconds, OUTPUT_SAMPLE_RATE } from './audio/wav';
export { AudioSegmenter } from './session/audioSegmenter';
export { UsageMeter, type UsageFlat, type UsageSnapshot } from './session/usageMeter';
export { SessionOrchestrator, type OrchestratorState, type OrchestratorOptions } from './session/sessionOrchestrator';
export { runFilePipeline, type FilePipelineInput, type FilePipelineResult, type PipelineFrame } from './file/filePipeline';
export { computeDubTimeline, type DubPlacement, type DubSegmentTiming } from './file/dubTimeline';
export { buildBilingualTxt, buildSrt, formatSrtTime, type SrtCue } from './file/srt';
export { BYTES_PER_MS_24K, mixdownDubPcm, type MixdownInput } from './file/dubMixdown';
export { MAX_FRAME_BYTES, MAX_FRAME_FPS, filterOversizedFrames, rawBytesOfBase64 } from './file/imageRules';
